whew-are-you-BE/whewareyou/settings.py
- fix RDS 중복 엔트리 settings.py
<br/>
<br/>
- 내일 할 일
<br/>
=> fix: DB 중복 삭제

whew-are-you-BE/requirements.txt
=> fix: add missing mysqlclient

whew-are-you-BE/whewareyou/settings.py
- 누락된 cors 미들웨어 추가
<br/>
<br/>
- 내일 할 일
<br/>
=> fix: cors 미들웨어 누락

whew-are-you-BE/whewareyou/settings.py
=> fix: cors 미들웨어 수정

whew-are-you-BE/whewareyou/settings.py
- 로컬 sqlite DB가 아닌 RDS를 가리키도록 수정
<br/>
<br/>
- 내일 할 일
<br/>
=> fix: DB hostname을 RDS 가리키도록 수정

whew-are-you-BE/typetest/views.py, whew-are-you-BE/whewareyou/settings.py
- 기존에 이전 버튼을 고려하지 않아 이전 버튼을 눌러도 기존의 데이터가 남아 있는 오류가 있었다.
- 해당 오류를 수정하였다
<br/>
<br/>
- 배포
<br/>
=> 유형화테스트 이전  버튼을 고려한 수정

whew-are-you-BE/users/serializers.py, whew-are-you-BE/users/views.py
요청 기능 구현 후 뒷정리를 했습니다. 
학교이메일이 아닌 타 메일로 인증할 경우 '멋쟁이사자처럼대학'이라 학교명이 등록됩니다.
<br/>
<br/>
- 내일 할 일
<br/>
=> chore: 앞선 두 커밋 뒷정리

whew-are-you-BE/users/views.py
GET에 본문을 넣지 맙시다.
<br/>
<br/>
- 내일 할 일
<br/>
=> fix: username 중복체크 query string으로 변경

whew-are-you-BE/review_information/review_urls.py, whew-are-you-BE/typetest/views.py
=> feat: 타입 응답 수정, 내용 응답

whew-are-you-BE/review_information/views.py, whew-are-you-BE/typetest/views.py
=> feat: 유형화 테스트 답변 객체 저장 취소

whew-are-you-BE/review_information/review_urls.py, whew-are-you-BE/review_information/serializers.py, whew-are-you-BE/review_information/views.py
- 좋아요 반영/취소
- 보관함 반영/취소
<br/>
<br/>
- 댓글 구현
<br/>
=> feat: 후기글 좋아요, 보관함 기능 추가

whew-are-you-BE/review_information/views.py
- 댓글에 권한을 추가(IsAuthenticatedOrReadOnly)
<br/>
<br/>
- 내일 할 일
<br/>
=> feat: 댓글 permissions 추가

whew-are-you-BE/portfolio/urls.py, whew-are-you-BE/portfolio/views.py
- 사용자의 모든 후기글 가져오기
- 기간 설정하여 후기글 가져오기
- 빙고 인증용 후기글만 가져오기
쿼리 스트링을 이용하였다
<br/>
<br/>
- 내일 할 일
<br/>
=> feat: 사용자 후기글 필터링 기능 추가

whew-are-you-BE/bingo/permissions.py, whew-are-you-BE/bingo/urls.py, whew-are-you-BE/bingo/views.py
- 빙고 API 최종화, 빠지거나 동작하지 않는 기능 점검
- bingo/items/{item_id} 를 더 이상 지원하지 않는 대신, 
- 프론트가 더 편하게 작업할 수 있도록 bingo/loc/{location}으로 엔드포인트 수정.
<br/>
<br/>
- 내일 할 일
- YYYY.MM.DD 변환
- recs 마무리 (추천순, 마감순, 보관함)
<br/>
=> feat: 빙고 API 칸 번호 (location)기반으로 변경, 이외 개선사항.

whew-are-you-BE/bingo/urls.py, whew-are-you-BE/bingo/views.py, whew-are-you-BE/review_information/models.py, whew-are-you-BE/whewareyou/settings.py
- 빙고 항목 마감순 API (pagination - 최대 개수 12개)
<br/>
<br/>
- 내일 할 일
- 보관함 API 만들기
<br/>
=> 빙고 항목 마감순 API

whew-are-you-BE/mypage/admin.py, whew-are-you-BE/mypage/apps.py, whew-are-you-BE/mypage/models.py, whew-are-you-BE/mypage/tests.py, whew-are-you-BE/mypage/urls.py, whew-are-you-BE/mypage/views.py, whew-are-you-BE/whewareyou/urls.py
- 마이페이지 기능이 추가되었습니다.
- 당분간 포인트는 1000포인트로 고정입니다.
<br/>
<br/>
- 내일 할 일
<br/>
=> feat: 마이페이지 APIView 추가

whew-are-you-BE/bingo/notice_urls.py, whew-are-you-BE/bingo/views.py
- 공고 글 하나 가져오기
<br/>
<br/>
- 검색 기능 구현
<br/>
=> feat: 공고 글 하나 가져오기

whew-are-you-BE/review_information/serializers.py
- 후기글 분류 한국어로도 반환
<br/>
<br/>
- 대댓글 기능 구현
<br/>
=> 후기글 분류 한국어로도 반환

whew-are-you-BE/bingo/serializers.py, whew-are-you-BE/review_information/review_urls.py, whew-are-you-BE/review_information/serializers.py
- 날짜 post 형식을 - 가 아니라 .으로 요청 받도록
<br/>
<br/>
- 내일 할 일
<br/>
=> feat: 날짜 post 형식 .으로

whew-are-you-BE/bingo/urls.py, whew-are-you-BE/bingo/views.py, whew-are-you-BE/review_information/review_urls.py
- 투두 상태 변경용 엔드포인트 추가
<br/>
<br/>
- 내일 할 일
<br/>
=> feat: 투두 상태 변경용 엔드포인트 추가

whew-are-you-BE/bingo/urls.py, whew-are-you-BE/bingo/views.py
- 진짜 슬래시 하나 빼먹었는데 ... 이미 pr 닫아버려서 다시... 흑흑
<br/>
<br/>
- 내일 할 일
<br/>
=> 진짜 별거 아닌 pr

whew-are-you-BE/bingo/serializers.py, whew-are-you-BE/bingo/views.py
- 공고글의 응답 형식을 알맞게 변환
<br/>
<br/>
- 내일 할 일
<br/>
=> 공고글 응답 형식 변경

whew-are-you-BE/review_information/views.py
- notice가 제대로 반환되도록 수정
<br/>
<br/>
- 내일 할 일
<br/>
=> fix: 검색 기능 수정

whew-are-you-BE/bingo/views.py, whew-are-you-BE/review_information/views.py
- 설정한 기간 내에 있는 글들만 가져오기
<br/>
<br/>
- 내일 할 일
<br/>
=> feat: 검색 기능에 날짜 검색 추가

whew-are-you-BE/bingo/models.py, whew-are-you-BE/bingo/serializers.py, whew-are-you-BE/review_information/models.py, whew-are-you-BE/review_information/serializers.py
- 후기글/공고의 좋아요 수, 댓글 수, 작성자 아이디까지 응답하도록 수정
<br/>
<br/>
- 내일 할 일
<br/>
=> feat: 좋아요 수, 댓글 수, 작성자 아이디 보이게

whew-are-you-BE/review_information/serializers.py
- 날짜 오류 수정
<br/>
<br/>
- 내일 할 일
<br/>
=> fix: 날짜 수정으로 인한 시리얼라이저 오류 수정

whew-are-you-BE/review_information/serializers.py
- 사용자가 하트를 눌렀는지 여부 
<br/>
<br/>
- 내일 할 일
<br/>
=> feat: 하트 여부

whew-are-you-BE/review_information/serializers.py
- 댓글 응답 유형 사진이 ㅂ여요
<br/>
<br/>
- 내일 할 일
<br/>
=> feat: 댓글 유형 사진 보이게

whew-are-you-BE/review_information/models.py
- 날짜 auto_now_add = True 설정
<br/>
<br/>
- 내일 할 일
<br/>
=> 후기글 post 오류 수정

whew-are-you-BE/review_information/serializers.py
- date 필드는 필수 x
<br/>
<br/>
- 내일 할 일
<br/>
=> fix: date 필드 필수 x

whew-are-you-BE/mypage/views.py
=> feat: 유형 국문으로 변환 제공

whew-are-you-BE/typetest/views.py
- 응답에 사용자 이름이 뜨도록
<br/>
<br/>
- 내일 할 일
<br/>
=> feat: 유형 테스트 사용자이름

whew-are-you-BE/review_information/models.py
=> feat: 댓글 post

whew-are-you-BE/portfolio/views.py
=> feat: 포트폴리오 get 했ㅇ을 때 존재하지 않으면 생성

whew-are-you-BE/portfolio/serializers.py
- 포트폴리오 get 했을 때 객체 없으면 생성
- 시리얼라이저 날짜 형태를 YYYY.MM.DD로
<br/>
<br/>
- 내일 할 일
<br/>
=> feat: get 했을 때 객체 없으면 생성 + 시리얼라이저 날짜 형태 .으로

whew-are-you-BE/review_information/serializers.py
**feat: 인증용 후기글 요청시 투두 포함**
영향 받는 엔드포인트 : (적어도 의도한건)
GET /review/
GET /review/{review_id}/ 
review_information/ReviewDetailAPIView 을 수정하고자 -> review_information/ReviewGETSerializer 수정
<br/>
<br/>
- 내일 할 일
<br/>
=> feat: 인증용 후기글 요청시 투두 포함

whew-are-you-BE/review_information/serializers.py
InformationGETSerializer에서 이제
그냥 일괄적으로 '휴알유'라고 옵니다.
Information 모델은 사실상 휴알유 포스트 용도이므로...
<br/>
<br/>
- 내일 할 일
<br/>
=> feat: 정보글(휴알유 제공)에 large_category_display 추가

whew-are-you-BE/portfolio/serializers.py
=> feat: 포트폴리오 시리얼라이저 birth는 피수 X

whew-are-you-BE/bingo/serializers.py
- 필수 아니게
<br/>
<br/>
- 내일 할 일
<br/>
=> 디데이 필드 필수 여부 수정

whew-are-you-BE/bingo/views.py
- 디데이 put 응답 형식 변경
<br/>
<br/>
- 내일 할 일
<br/>
=> feat: 디데이 짜잘 수정

whew-are-you-BE/bingo/serializers.py
=> 각 ProvidedBingoItem에서, is_notice True일때 notice_id같이 반환

whew-are-you-BE/bingo/views.py
=> fix: 빙고 인증용 후기글 오류 수정

whew-are-you-BE/bingo/views.py
[직접 입력 빙고 항목에 large_category추가]
POST /bingo와
GET /bingo 가 영향받음.
<br/>
<br/>
- 내일 할 일
<br/>
=> 직접 입력 빙고 항목에 large_category추가

whew-are-you-BE/typetest/views.py
=> fix: user_type_display랑 원본 유저명 같이 반환

whew-are-you-BE/review_information/views.py
후기글 불러오기 시 날짜 제한 추가
[영향받는 view 및 url]
- ReviewAPIView  === /review/
- FetchRelatedReviewsAPIView === /review/related/{id}/
- SearchAPIView === /review/?search=어쩌구
단 UTC+9인지 좀 헷갈린다.... 함 확인해봐라
<br/>
<br/>
- 내일 할 일
<br/>
=> feat: 안정성을 위해 후기글 날짜 제한 추가

whew-are-you-BE/review_information/views.py, whew-are-you-BE/whewareyou/settings.py
/review/ => 이때 요청 처리에 1분 이상 소요되어 , 캐시 도입.
/search/
/review/related/
<br/>
<br/>
- 내일 할 일
<br/>
=> feat: 후기글 불러오기에 LocMemCached 추가

whew-are-you-BE/mypage/views.py
=> feat: 마이페이지 유형 영문/국문 모두 반환

whew-are-you-BE/bingo/serializers.py
=> feat: BingoObjAPIView에서 CustomBingoItem의 large_category_display 추가

whew-are-you-BE/portfolio/serializers.py
- 포트폴리오 시리얼라이저 변경
<br/>
<br/>
- 내일 할 일
<br/>
=> feat: 포트폴리오 시리얼라이저에 사용자 타입이랑 사진을 반환

whew-are-you-BE/review_information/views.py, whew-are-you-BE/whewareyou/settings.py
This reverts commit 6e0d7e97337bedf10f5299214060b7e83c824729.
<br/>
<br/>
- 내일 할 일
<br/>
=> Revert "feat: 후기글 불러오기에 LocMemCached 추가"

whew-are-you-BE/typetest/views.py
- fix: 로그인하지 않은 상태 유형테스트시 user_type_display누락 오류 해결
<br/>
<br/>
- 내일 할 일
<br/>
=> fix: 로그인하지 않은 상태 유형테스트시 user_type_display누락 오류
